### ISSUE TITLE
Can we get a license on this?

### ISSUE THREAD

**Issue by nwkotto** [martellaj/chrome-extension-react-typescript-boilerplate#5]
Hi there! I'm hoping to use this as a basis for a small project but I'm not sure what the legal implications would be. I'm assuming that you're intending for this to be freely usable, so would you mind adding a [license](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)? Thanks!

**Comment by martellaj** [comment]
@nwkotto Done. 👍

Please share your project whenever maybe I'll add it to the README or something. 🤷‍♀️

**Comment by nwkotto** [comment]
Awesome, thanks (and for the quick response)! Will see how it pans out and will let you know if we do make some progress. Thanks for creating this boilerplate -- really saved us some time.
