### ISSUE TITLE
Windows 10: Google Chrome: Loading extension failed "Could not load background script 'js/eventPage.js'."

### ISSUE THREAD

**Issue by seasaltseasalt** [martellaj/chrome-extension-react-typescript-boilerplate#8]
When I attempt to load extension per installation instructions, gives me this error.
Where do I look?

Go to chrome://extensions in Google Chrome
With the developer mode checkbox ticked, click Load unpacked extension... and select the dist folder from this repo

After selecting Load Unpacked, and then selecting the DIST folder, Google Chrome returns error

Could not load background script 'js/eventPage.js'.
Could not load manifest.

**Comment by martellaj** [comment]
@seasaltseasalt The first step is to build the project. Based on the error message you're getting, it looks like there's no JavaScript file present which means you didn't build the project.
