### ISSUE TITLE
Retrieving Messages in foreground script from popup

### ISSUE THREAD

**Issue by kubo550** [martellaj/chrome-extension-react-typescript-boilerplate#9]
Hello, it is possible to get message directly from popup to content srcipt?

This not working:

//popup.js
` <button onClick={() => chrome.runtime.sendMessage({ msg: "hello" })}> click me </button> `

// foreground.js
` chrome.runtime.onMessage.addListener((request, sender, sendResponse) => { `
  `  console.log(request); `
`    console.log("I have message!"); `
 `   return true;`
` });  ` 
I am asking cause because in pure js it goes with no problem

**Comment by martellaj** [comment]
Sorry for the SUPER late response to this. But for completeness's sake - no, you cannot send a message in that way. I implemented a function I use in my popup.js file that can send a message to the content script.

```
export default function sendMessageToContentScript(
  action: string,
  extraData?: string
) {
  chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
    chrome.tabs.sendMessage(tabs[0].id, { action, extraData });
  });
}
```
